name: Save working directory
description: Save working directory, preserving permissions
inputs:
  name:
    description: a name to reference with actions/load

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v8
      id: platform
      with:
        result-encoding: string
        script: |
          const os = require('os');
          return os.platform();
    - name: Tar working directory
      shell: bash
      run: |
        wdir="$(pwd)"
        parent="$(dirname "$wdir")"
        target="$(basename "$wdir")"
        tar ${{ steps.platform.outputs.result == 'win32' && '--force-local' || '' }} -C "$parent" -cf "${{ runner.temp }}/${{ inputs.name }}.tar" "$target"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: '${{ runner.temp }}/${{ inputs.name }}.tar'
        name: ${{ inputs.name }}
        overwrite: true
