/**
 * @id prebid/webgl-readpixels
 * @name Access to webgl rendering context readPixels
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl RenderingContext.readPixels
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl") and
  api = invocation.getAPropertyRead("readPixels")
select api, "readPixels is an indicator of fingerprinting, weighed 15.25 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
