/**
 * @id prebid/devicemotionevent-acceleration
 * @name Potential access to DeviceMotionEvent.acceleration
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of acceleration
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from PropRef api
where  
  api.getPropertyName() = "acceleration"
select api, "acceleration is an indicator of fingerprinting, weighed 57.38 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
