/**
 * @id prebid/navigator-webdriver
 * @name Access to navigator.webdriver
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.webdriver
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("webdriver")
select api, "webdriver is an indicator of fingerprinting, weighed 32.66 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
