// this file is autogenerated, see fingerprintApis.mjs

class SensorProperty extends string {

  float weight; 
  
  SensorProperty() {
      
      ( this = "start"  and weight = 52.76 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
