/**
 * @id prebid/window-outerheight
 * @name Access to window.outerHeight
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.outerHeight
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("outerHeight")
select api, "outerHeight is an indicator of fingerprinting, weighed 181.21 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
