// this file is autogenerated, see fingerprintApis.mjs

class RenderingContextProperty extends string {

  float weight; 
  string contextType; 
  
  RenderingContextProperty() {
      
      ( this = "getExtension"  and weight = 22.26  and contextType = "webgl" )
       or 
      ( this = "getParameter"  and weight = 24.79  and contextType = "webgl" )
       or 
      ( this = "getExtension"  and weight = 36.36  and contextType = "webgl2" )
       or 
      ( this = "getParameter"  and weight = 32.65  and contextType = "webgl2" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 952.81  and contextType = "webgl" )
       or 
      ( this = "getContextAttributes"  and weight = 1440.97  and contextType = "webgl" )
       or 
      ( this = "getSupportedExtensions"  and weight = 1346.7  and contextType = "webgl" )
       or 
      ( this = "getImageData"  and weight = 57.15  and contextType = "2d" )
       or 
      ( this = "isPointInPath"  and weight = 4600.59  and contextType = "2d" )
       or 
      ( this = "getSupportedExtensions"  and weight = 377.95  and contextType = "webgl2" )
       or 
      ( this = "getContextAttributes"  and weight = 157.07  and contextType = "webgl2" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 153.5  and contextType = "webgl2" )
       or 
      ( this = "readPixels"  and weight = 1474.47  and contextType = "webgl2" )
       or 
      ( this = "readPixels"  and weight = 42.18  and contextType = "webgl" )
       or 
      ( this = "measureText"  and weight = 50.73  and contextType = "2d" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getContextType() {
    result = contextType
  }
  
} 
