/**
 * @id prebid/domevent-deviceorientation-gamma
 * @name Access to domEvent gamma (deviceorientation)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of gamma on domEvent (deviceorientation)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("deviceorientation") and
  api = target.getAPropertyRead("gamma")
select api, "gamma is an indicator of fingerprinting, weighed 395.62 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
