/**
 * @id prebid/window-outerwidth
 * @name Access to window.outerWidth
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.outerWidth
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("outerWidth")
select api, "outerWidth is an indicator of fingerprinting, weighed 102.66 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
