/**
 * @id prebid/window-screenleft
 * @name Access to window.screenLeft
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.screenLeft
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("screenLeft")
select api, "screenLeft is an indicator of fingerprinting, weighed 286.83 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
