/**
 * @id prebid/gyroscope-z
 * @name Access to Gyroscope.z
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Gyroscope.z
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode inst, SourceNode api
where
  inst = instantiationOf("Gyroscope") and
  api = inst.getAPropertyRead("z")
select api, "z is an indicator of fingerprinting, weighed 4216.23 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
