/**
 * @id prebid/navigator-getgamepads
 * @name Access to navigator.getGamepads
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.getGamepads
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("getGamepads")
select api, "getGamepads is an indicator of fingerprinting, weighed 211.66 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
