// this file is autogenerated, see fingerprintApis.mjs

class GlobalObjectProperty0 extends string {

  float weight; 
  string global0; 
  
  GlobalObjectProperty0() {
      
      ( this = "availHeight"  and weight = 98.84  and global0 = "screen" )
       or 
      ( this = "availWidth"  and weight = 91.11  and global0 = "screen" )
       or 
      ( this = "colorDepth"  and weight = 42.4  and global0 = "screen" )
       or 
      ( this = "availTop"  and weight = 1745.92  and global0 = "screen" )
       or 
      ( this = "productSub"  and weight = 498.57  and global0 = "navigator" )
       or 
      ( this = "deviceMemory"  and weight = 51.66  and global0 = "navigator" )
       or 
      ( this = "pixelDepth"  and weight = 54.54  and global0 = "screen" )
       or 
      ( this = "availLeft"  and weight = 835.82  and global0 = "screen" )
       or 
      ( this = "orientation"  and weight = 39.76  and global0 = "screen" )
       or 
      ( this = "vendorSub"  and weight = 2146.6  and global0 = "navigator" )
       or 
      ( this = "webkitTemporaryStorage"  and weight = 42.82  and global0 = "navigator" )
       or 
      ( this = "hardwareConcurrency"  and weight = 63.77  and global0 = "navigator" )
       or 
      ( this = "appCodeName"  and weight = 187.2  and global0 = "navigator" )
       or 
      ( this = "onLine"  and weight = 20.46  and global0 = "navigator" )
       or 
      ( this = "webdriver"  and weight = 25.84  and global0 = "navigator" )
       or 
      ( this = "keyboard"  and weight = 7237.56  and global0 = "navigator" )
       or 
      ( this = "mediaDevices"  and weight = 149.44  and global0 = "navigator" )
       or 
      ( this = "storage"  and weight = 33.34  and global0 = "navigator" )
       or 
      ( this = "mediaCapabilities"  and weight = 26.27  and global0 = "navigator" )
       or 
      ( this = "permissions"  and weight = 77.06  and global0 = "navigator" )
       or 
      ( this = "presentation"  and weight = 29.83  and global0 = "navigator" )
       or 
      ( this = "permission"  and weight = 25.83  and global0 = "Notification" )
       or 
      ( this = "getBattery"  and weight = 33.11  and global0 = "navigator" )
       or 
      ( this = "requestMediaKeySystemAccess"  and weight = 33.9  and global0 = "navigator" )
       or 
      ( this = "webkitPersistentStorage"  and weight = 129.33  and global0 = "navigator" )
       or 
      ( this = "getGamepads"  and weight = 406.21  and global0 = "navigator" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
} 
