/**
 * @id prebid/navigator-mediacapabilities
 * @name Access to navigator.mediaCapabilities
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.mediaCapabilities
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("mediaCapabilities")
select api, "mediaCapabilities is an indicator of fingerprinting, weighed 123.84 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
