/**
 * @id prebid/domevent-devicemotion-rotationrate
 * @name Access to domEvent rotationRate (devicemotion)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of rotationRate on domEvent (devicemotion)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("devicemotion") and
  api = target.getAPropertyRead("rotationRate")
select api, "rotationRate is an indicator of fingerprinting, weighed 57.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
