/**
 * @id prebid/screen-availheight
 * @name Access to screen.availHeight
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.availHeight
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("availHeight")
select api, "availHeight is an indicator of fingerprinting, weighed 70.68 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
