/**
 * @id prebid/devicemotionevent-accelerationincludinggravity
 * @name Potential access to DeviceMotionEvent.accelerationIncludingGravity
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of accelerationIncludingGravity
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from PropRef api
where  
  api.getPropertyName() = "accelerationIncludingGravity"
select api, "accelerationIncludingGravity is an indicator of fingerprinting, weighed 166.43 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
