/**
 * @id prebid/2d-getimagedata
 * @name Access to 2d rendering context getImageData
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  2d RenderingContext.getImageData
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("2d") and
  api = invocation.getAPropertyRead("getImageData")
select api, "getImageData is an indicator of fingerprinting, weighed 40.74 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
