/**
 * @id prebid/navigator-permissions
 * @name Access to navigator.permissions
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.permissions
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("permissions")
select api, "permissions is an indicator of fingerprinting, weighed 83.98 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
