/**
 * @id prebid/devicemotionevent-rotationrate
 * @name Potential access to DeviceMotionEvent.rotationRate
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of rotationRate
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from PropRef api
where  
  api.getPropertyName() = "rotationRate"
select api, "rotationRate is an indicator of fingerprinting, weighed 59.32 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
