/**
 * @id prebid/navigator-vendorsub
 * @name Access to navigator.vendorSub
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.vendorSub
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("vendorSub")
select api, "vendorSub is an indicator of fingerprinting, weighed 1543.86 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
