/**
 * @id prebid/window-indexeddb
 * @name Access to window.indexedDB
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.indexedDB
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("indexedDB")
select api, "indexedDB is an indicator of fingerprinting, weighed 17.63 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
