// this file is autogenerated, see fingerprintApis.mjs

class GlobalConstructor extends string {

  float weight; 
  
  GlobalConstructor() {
      
      ( this = "OfflineAudioContext"  and weight = 225.31 )
       or 
      ( this = "RTCPeerConnection"  and weight = 34.53 )
       or 
      ( this = "SharedWorker"  and weight = 75.74 )
       or 
      ( this = "Gyroscope"  and weight = 50.8 )
       or 
      ( this = "AudioWorkletNode"  and weight = 119.39 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
