/**
 * @id prebid/devicemotion-rotationrate
 * @name Access to devicemotion.rotationRate
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of rotationRate on devicemotion events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("devicemotion") and
  api = event.getAPropertyRead("rotationRate")
select api, "rotationRate is an indicator of fingerprinting, weighed 57.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
