/**
 * @id prebid/navigator-keyboard
 * @name Access to navigator.keyboard
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.keyboard
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("keyboard")
select api, "keyboard is an indicator of fingerprinting, weighed 938.38 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
