// this file is autogenerated, see fingerprintApis.mjs

class GlobalObjectProperty1 extends string {

  float weight; 
  string global0; 
  string global1; 
  
  GlobalObjectProperty1() {
      
      ( this = "enumerateDevices"  and weight = 361.7  and global0 = "navigator"  and global1 = "mediaDevices" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
  string getGlobal1() {
    result = global1
  }
  
} 
