/**
 * @id prebid/deviceorientation-gamma
 * @name Access to deviceorientation.gamma
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of gamma on deviceorientation events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("deviceorientation") and
  api = event.getAPropertyRead("gamma")
select api, "gamma is an indicator of fingerprinting, weighed 395.62 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
