/**
 * @id prebid/window-opendatabase
 * @name Access to window.openDatabase
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.openDatabase
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("openDatabase")
select api, "openDatabase is an indicator of fingerprinting, weighed 143.97 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
