/**
 * @id prebid/webgl2-getshaderprecisionformat
 * @name Access to webgl2 rendering context getShaderPrecisionFormat
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl2 RenderingContext.getShaderPrecisionFormat
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl2") and
  api = invocation.getAPropertyRead("getShaderPrecisionFormat")
select api, "getShaderPrecisionFormat is an indicator of fingerprinting, weighed 103.05 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
