/**
 * @id prebid/domevent-devicemotion-acceleration
 * @name Access to domEvent acceleration (devicemotion)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of acceleration on domEvent (devicemotion)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("devicemotion") and
  api = target.getAPropertyRead("acceleration")
select api, "acceleration is an indicator of fingerprinting, weighed 58.05 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
