/**
 * @id prebid/devicemotion-acceleration
 * @name Access to devicemotion.acceleration
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of acceleration on devicemotion events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("devicemotion") and
  api = event.getAPropertyRead("acceleration")
select api, "acceleration is an indicator of fingerprinting, weighed 58.05 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
