/**
 * @id prebid/window-screenx
 * @name Access to window.screenX
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.screenX
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("screenX")
select api, "screenX is an indicator of fingerprinting, weighed 301.79 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
