/**
 * @id prebid/deviceorientation-absolute
 * @name Access to deviceorientation.absolute
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of absolute on deviceorientation events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("deviceorientation") and
  api = event.getAPropertyRead("absolute")
select api, "absolute is an indicator of fingerprinting, weighed 387.12 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
