/**
 * @id prebid/domevent-deviceorientation-beta
 * @name Access to domEvent beta (deviceorientation)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of beta on domEvent (deviceorientation)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("deviceorientation") and
  api = target.getAPropertyRead("beta")
select api, "beta is an indicator of fingerprinting, weighed 1075.3 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
