/**
 * @id prebid/webgl2-getparameter
 * @name Access to webgl2 rendering context getParameter
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl2 RenderingContext.getParameter
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl2") and
  api = invocation.getAPropertyRead("getParameter")
select api, "getParameter is an indicator of fingerprinting, weighed 41.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
