// this file is autogenerated, see fingerprintApis.mjs

class EventProperty extends string {

  float weight; 
  string event; 
  
  EventProperty() {
      
      ( this = "accelerationIncludingGravity"  and weight = 158.1  and event = "devicemotion" )
       or 
      ( this = "beta"  and weight = 887.22  and event = "deviceorientation" )
       or 
      ( this = "gamma"  and weight = 361.7  and event = "deviceorientation" )
       or 
      ( this = "alpha"  and weight = 354.09  and event = "deviceorientation" )
       or 
      ( this = "candidate"  and weight = 69.81  and event = "icecandidate" )
       or 
      ( this = "acceleration"  and weight = 64.92  and event = "devicemotion" )
       or 
      ( this = "rotationRate"  and weight = 64.37  and event = "devicemotion" )
       or 
      ( this = "absolute"  and weight = 709.73  and event = "deviceorientation" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getEvent() {
    result = event
  }
  
} 
