/**
 * @id prebid/deviceorientation-beta
 * @name Access to deviceorientation.beta
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of beta on deviceorientation events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("deviceorientation") and
  api = event.getAPropertyRead("beta")
select api, "beta is an indicator of fingerprinting, weighed 1075.3 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
