// this file is autogenerated, see fingerprintApis.mjs

class GlobalObjectProperty0 extends string {

  float weight; 
  string global0; 
  
  GlobalObjectProperty0() {
      
      ( this = "availHeight"  and weight = 65.33  and global0 = "screen" )
       or 
      ( this = "availWidth"  and weight = 61.95  and global0 = "screen" )
       or 
      ( this = "colorDepth"  and weight = 38.5  and global0 = "screen" )
       or 
      ( this = "availTop"  and weight = 1305.37  and global0 = "screen" )
       or 
      ( this = "plugins"  and weight = 15.16  and global0 = "navigator" )
       or 
      ( this = "deviceMemory"  and weight = 64.15  and global0 = "navigator" )
       or 
      ( this = "getBattery"  and weight = 41.16  and global0 = "navigator" )
       or 
      ( this = "webdriver"  and weight = 27.64  and global0 = "navigator" )
       or 
      ( this = "permission"  and weight = 24.67  and global0 = "Notification" )
       or 
      ( this = "storage"  and weight = 35.77  and global0 = "navigator" )
       or 
      ( this = "onLine"  and weight = 18.84  and global0 = "navigator" )
       or 
      ( this = "pixelDepth"  and weight = 45.77  and global0 = "screen" )
       or 
      ( this = "availLeft"  and weight = 624.44  and global0 = "screen" )
       or 
      ( this = "orientation"  and weight = 34.16  and global0 = "screen" )
       or 
      ( this = "vendorSub"  and weight = 1873.27  and global0 = "navigator" )
       or 
      ( this = "productSub"  and weight = 381.87  and global0 = "navigator" )
       or 
      ( this = "webkitTemporaryStorage"  and weight = 37.97  and global0 = "navigator" )
       or 
      ( this = "hardwareConcurrency"  and weight = 51.78  and global0 = "navigator" )
       or 
      ( this = "appCodeName"  and weight = 173.35  and global0 = "navigator" )
       or 
      ( this = "keyboard"  and weight = 1722.82  and global0 = "navigator" )
       or 
      ( this = "mediaDevices"  and weight = 149.07  and global0 = "navigator" )
       or 
      ( this = "mediaCapabilities"  and weight = 142.34  and global0 = "navigator" )
       or 
      ( this = "permissions"  and weight = 89.71  and global0 = "navigator" )
       or 
      ( this = "webkitPersistentStorage"  and weight = 134.12  and global0 = "navigator" )
       or 
      ( this = "requestMediaKeySystemAccess"  and weight = 18.22  and global0 = "navigator" )
       or 
      ( this = "getGamepads"  and weight = 209.55  and global0 = "navigator" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
} 
