/**
 * @id prebid/domevent-devicemotion-accelerationincludinggravity
 * @name Access to domEvent accelerationIncludingGravity (devicemotion)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of accelerationIncludingGravity on domEvent (devicemotion)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("devicemotion") and
  api = target.getAPropertyRead("accelerationIncludingGravity")
select api, "accelerationIncludingGravity is an indicator of fingerprinting, weighed 149.23 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
