/**
 * @id prebid/gyroscope-y
 * @name Access to Gyroscope.y
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Gyroscope.y
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode inst, SourceNode api
where
  inst = callTo("Gyroscope") and
  api = inst.getAPropertyRead("y")
select api, "y is an indicator of fingerprinting, weighed 5043.14 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
