// this file is autogenerated, see fingerprintApis.mjs

class GlobalConstructor extends string {

  float weight; 
  
  GlobalConstructor() {
      
      ( this = "OfflineAudioContext"  and weight = 190.93 )
       or 
      ( this = "RTCPeerConnection"  and weight = 34.85 )
       or 
      ( this = "SharedWorker"  and weight = 85.13 )
       or 
      ( this = "Gyroscope"  and weight = 55.85 )
       or 
      ( this = "AudioWorkletNode"  and weight = 99.28 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
