/**
 * @id prebid/notification-permission
 * @name Access to Notification.permission
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Notification.permission
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("Notification") and
  api = prop.getAPropertyRead("permission")
select api, "permission is an indicator of fingerprinting, weighed 22.63 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
