/**
 * @id prebid/webgl-getcontextattributes
 * @name Access to webgl rendering context getContextAttributes
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl RenderingContext.getContextAttributes
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl") and
  api = invocation.getAPropertyRead("getContextAttributes")
select api, "getContextAttributes is an indicator of fingerprinting, weighed 2131.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
