/**
 * @id prebid/screen-availtop
 * @name Access to screen.availTop
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.availTop
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("availTop")
select api, "availTop is an indicator of fingerprinting, weighed 1240.09 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
