/**
 * @id prebid/rtcpeerconnection
 * @name Use of RTCPeerConnection
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of RTCPeerConnection
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = instantiationOf("RTCPeerConnection")
select api, "RTCPeerConnection is an indicator of fingerprinting, weighed 47.04 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
