/**
 * @id prebid/webgl-getparameter
 * @name Access to webgl rendering context getParameter
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl RenderingContext.getParameter
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl") and
  api = invocation.getAPropertyRead("getParameter")
select api, "getParameter is an indicator of fingerprinting, weighed 22.92 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
