// this file is autogenerated, see fingerprintApis.mjs

class GlobalTypeProperty0 extends string {

  float weight; 
  string global0; 
  
  GlobalTypeProperty0() {
      
      ( this = "x"  and weight = 7033.93  and global0 = "Gyroscope" )
       or 
      ( this = "y"  and weight = 7033.93  and global0 = "Gyroscope" )
       or 
      ( this = "z"  and weight = 7033.93  and global0 = "Gyroscope" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
} 
