/**
 * @id prebid/screen-colordepth
 * @name Access to screen.colorDepth
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.colorDepth
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("colorDepth")
select api, "colorDepth is an indicator of fingerprinting, weighed 34.52 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
