// this file is autogenerated, see fingerprintApis.mjs

class GlobalVar extends string {

  float weight; 
  
  GlobalVar() {
      
      ( this = "devicePixelRatio"  and weight = 17.98 )
       or 
      ( this = "screenX"  and weight = 370.06 )
       or 
      ( this = "screenY"  and weight = 355.31 )
       or 
      ( this = "outerWidth"  and weight = 114.63 )
       or 
      ( this = "outerHeight"  and weight = 177.29 )
       or 
      ( this = "screenLeft"  and weight = 333.38 )
       or 
      ( this = "screenTop"  and weight = 330.29 )
       or 
      ( this = "indexedDB"  and weight = 22.97 )
       or 
      ( this = "openDatabase"  and weight = 31.35 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
