// this file is autogenerated, see fingerprintApis.mjs

class RenderingContextProperty extends string {

  float weight; 
  string contextType; 
  
  RenderingContextProperty() {
      
      ( this = "getImageData"  and weight = 55.51  and contextType = "2d" )
       or 
      ( this = "getParameter"  and weight = 30.58  and contextType = "webgl" )
       or 
      ( this = "measureText"  and weight = 46.82  and contextType = "2d" )
       or 
      ( this = "getParameter"  and weight = 70.22  and contextType = "webgl2" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 128.74  and contextType = "webgl2" )
       or 
      ( this = "getExtension"  and weight = 71.78  and contextType = "webgl2" )
       or 
      ( this = "getContextAttributes"  and weight = 190.28  and contextType = "webgl2" )
       or 
      ( this = "getSupportedExtensions"  and weight = 560.85  and contextType = "webgl2" )
       or 
      ( this = "getExtension"  and weight = 26.27  and contextType = "webgl" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 1175.17  and contextType = "webgl" )
       or 
      ( this = "getContextAttributes"  and weight = 1998.53  and contextType = "webgl" )
       or 
      ( this = "getSupportedExtensions"  and weight = 1388.64  and contextType = "webgl" )
       or 
      ( this = "readPixels"  and weight = 22.43  and contextType = "webgl" )
       or 
      ( this = "isPointInPath"  and weight = 5210.68  and contextType = "2d" )
       or 
      ( this = "readPixels"  and weight = 610.19  and contextType = "webgl2" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getContextType() {
    result = contextType
  }
  
} 
