/**
 * @id prebid/audioworkletnode
 * @name Use of AudioWorkletNode
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of AudioWorkletNode
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = callTo("AudioWorkletNode")
select api, "AudioWorkletNode is an indicator of fingerprinting, weighed 17.63 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
