/**
 * @id prebid/domevent-deviceorientation-alpha
 * @name Access to domEvent alpha (deviceorientation)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of alpha on domEvent (deviceorientation)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("deviceorientation") and
  api = target.getAPropertyRead("alpha")
select api, "alpha is an indicator of fingerprinting, weighed 366.53 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
