// this file is autogenerated, see fingerprintApis.mjs

class DOMMethod extends string {

  float weight; 
  string type; 
  
  DOMMethod() {
      
      ( this = "toDataURL"  and weight = 32.64  and type = "HTMLCanvasElement" )
       or 
      ( this = "getChannelData"  and weight = 1009.41  and type = "AudioBuffer" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getType() {
    result = type
  }
  
} 
