/**
 * @id prebid/webgl-getsupportedextensions
 * @name Access to webgl rendering context getSupportedExtensions
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl RenderingContext.getSupportedExtensions
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl") and
  api = invocation.getAPropertyRead("getSupportedExtensions")
select api, "getSupportedExtensions is an indicator of fingerprinting, weighed 1058.69 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
