// this file is autogenerated, see fingerprintApis.mjs

class GlobalTypeProperty1 extends string {

  float weight; 
  string global0; 
  string global1; 
  
  GlobalTypeProperty1() {
      
      ( this = "resolvedOptions"  and weight = 18.83  and global0 = "Intl"  and global1 = "DateTimeFormat" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
  string getGlobal1() {
    result = global1
  }
  
} 
