/**
 * @id prebid/window-devicepixelratio
 * @name Access to window.devicePixelRatio
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.devicePixelRatio
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("devicePixelRatio")
select api, "devicePixelRatio is an indicator of fingerprinting, weighed 18.68 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
