/**
 * @id prebid/navigator-webkittemporarystorage
 * @name Access to navigator.webkitTemporaryStorage
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.webkitTemporaryStorage
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("webkitTemporaryStorage")
select api, "webkitTemporaryStorage is an indicator of fingerprinting, weighed 39.66 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
