// this file is autogenerated, see fingerprintApis.mjs

class EventProperty extends string {

  float weight; 
  string event; 
  
  EventProperty() {
      
      ( this = "accelerationIncludingGravity"  and weight = 159.98  and event = "devicemotion" )
       or 
      ( this = "beta"  and weight = 851.21  and event = "deviceorientation" )
       or 
      ( this = "gamma"  and weight = 303.39  and event = "deviceorientation" )
       or 
      ( this = "alpha"  and weight = 768.07  and event = "deviceorientation" )
       or 
      ( this = "candidate"  and weight = 45.34  and event = "icecandidate" )
       or 
      ( this = "acceleration"  and weight = 63.39  and event = "devicemotion" )
       or 
      ( this = "rotationRate"  and weight = 63.13  and event = "devicemotion" )
       or 
      ( this = "absolute"  and weight = 402.37  and event = "deviceorientation" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getEvent() {
    result = event
  }
  
} 
