/**
 * @id prebid/navigator-cookieenabled
 * @name Access to navigator.cookieEnabled
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.cookieEnabled
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("cookieEnabled")
select api, "cookieEnabled is an indicator of fingerprinting, weighed 15.3 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
