/**
 * @id prebid/navigator-getbattery
 * @name Access to navigator.getBattery
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.getBattery
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("getBattery")
select api, "getBattery is an indicator of fingerprinting, weighed 117.75 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
