/**
 * @id prebid/domevent-deviceorientation-absolute
 * @name Access to domEvent absolute (deviceorientation)
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of absolute on domEvent (deviceorientation)
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import domEvent
from SourceNode target, SourceNode api
where
  target = domEvent("deviceorientation") and
  api = target.getAPropertyRead("absolute")
select api, "absolute is an indicator of fingerprinting, weighed 387.12 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
