/**
 * @id prebid/sensor-start
 * @name Access to sensor start
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of start on sensor
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import sensor
from SourceNode target, SourceNode api
where
  target = sensor() and
  api = target.getAPropertyRead("start")
select api, "start is an indicator of fingerprinting, weighed 123.75 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
