/**
 * @id prebid/navigator-webkitpersistentstorage
 * @name Access to navigator.webkitPersistentStorage
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.webkitPersistentStorage
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("webkitPersistentStorage")
select api, "webkitPersistentStorage is an indicator of fingerprinting, weighed 132.06 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
