/**
 * @id prebid/gyroscope
 * @name Use of Gyroscope
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Gyroscope
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = instantiationOf("Gyroscope")
select api, "Gyroscope is an indicator of fingerprinting, weighed 189.7 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
