/**
 * @id prebid/screen-availwidth
 * @name Access to screen.availWidth
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.availWidth
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("availWidth")
select api, "availWidth is an indicator of fingerprinting, weighed 67.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
