// this file is autogenerated, see fingerprintApis.mjs

class GlobalObjectProperty0 extends string {

  float weight; 
  string global0; 
  
  GlobalObjectProperty0() {
      
      ( this = "availHeight"  and weight = 96.62  and global0 = "screen" )
       or 
      ( this = "availWidth"  and weight = 89.95  and global0 = "screen" )
       or 
      ( this = "colorDepth"  and weight = 42.26  and global0 = "screen" )
       or 
      ( this = "availTop"  and weight = 1353.4  and global0 = "screen" )
       or 
      ( this = "deviceMemory"  and weight = 61.93  and global0 = "navigator" )
       or 
      ( this = "pixelDepth"  and weight = 51.98  and global0 = "screen" )
       or 
      ( this = "availLeft"  and weight = 661.19  and global0 = "screen" )
       or 
      ( this = "orientation"  and weight = 34.72  and global0 = "screen" )
       or 
      ( this = "vendorSub"  and weight = 2725.72  and global0 = "navigator" )
       or 
      ( this = "productSub"  and weight = 448.44  and global0 = "navigator" )
       or 
      ( this = "webkitTemporaryStorage"  and weight = 37.16  and global0 = "navigator" )
       or 
      ( this = "hardwareConcurrency"  and weight = 72.55  and global0 = "navigator" )
       or 
      ( this = "appCodeName"  and weight = 160.76  and global0 = "navigator" )
       or 
      ( this = "onLine"  and weight = 19.69  and global0 = "navigator" )
       or 
      ( this = "webdriver"  and weight = 25.44  and global0 = "navigator" )
       or 
      ( this = "keyboard"  and weight = 3172.04  and global0 = "navigator" )
       or 
      ( this = "mediaDevices"  and weight = 151.88  and global0 = "navigator" )
       or 
      ( this = "storage"  and weight = 38.66  and global0 = "navigator" )
       or 
      ( this = "mediaCapabilities"  and weight = 31.44  and global0 = "navigator" )
       or 
      ( this = "permissions"  and weight = 66.89  and global0 = "navigator" )
       or 
      ( this = "presentation"  and weight = 32.86  and global0 = "navigator" )
       or 
      ( this = "permission"  and weight = 25.92  and global0 = "Notification" )
       or 
      ( this = "getBattery"  and weight = 35.48  and global0 = "navigator" )
       or 
      ( this = "requestMediaKeySystemAccess"  and weight = 34.46  and global0 = "navigator" )
       or 
      ( this = "webkitPersistentStorage"  and weight = 132.3  and global0 = "navigator" )
       or 
      ( this = "getGamepads"  and weight = 254.4  and global0 = "navigator" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getGlobal0() {
    result = global0
  }
  
} 
