/**
 * @id prebid/sharedworker
 * @name Use of SharedWorker
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of SharedWorker
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = callTo("SharedWorker")
select api, "SharedWorker is an indicator of fingerprinting, weighed 78.14 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
