/**
 * @id prebid/navigator-productsub
 * @name Access to navigator.productSub
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.productSub
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("productSub")
select api, "productSub is an indicator of fingerprinting, weighed 482.29 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
