/**
 * @id prebid/navigator-storage
 * @name Access to navigator.storage
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.storage
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("storage")
select api, "storage is an indicator of fingerprinting, weighed 143.61 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
