// this file is autogenerated, see fingerprintApis.mjs

class EventProperty extends string {

  float weight; 
  string event; 
  
  EventProperty() {
      
      ( this = "accelerationIncludingGravity"  and weight = 144.34  and event = "devicemotion" )
       or 
      ( this = "beta"  and weight = 922.49  and event = "deviceorientation" )
       or 
      ( this = "gamma"  and weight = 312.57  and event = "deviceorientation" )
       or 
      ( this = "alpha"  and weight = 840.16  and event = "deviceorientation" )
       or 
      ( this = "candidate"  and weight = 44.63  and event = "icecandidate" )
       or 
      ( this = "acceleration"  and weight = 62.48  and event = "devicemotion" )
       or 
      ( this = "rotationRate"  and weight = 61.83  and event = "devicemotion" )
       or 
      ( this = "absolute"  and weight = 360.18  and event = "deviceorientation" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getEvent() {
    result = event
  }
  
} 
