// this file is autogenerated, see fingerprintApis.mjs

class GlobalConstructor extends string {

  float weight; 
  
  GlobalConstructor() {
      
      ( this = "OfflineAudioContext"  and weight = 224.73 )
       or 
      ( this = "SharedWorker"  and weight = 83.39 )
       or 
      ( this = "RTCPeerConnection"  and weight = 33.57 )
       or 
      ( this = "Gyroscope"  and weight = 58.22 )
       or 
      ( this = "AudioWorkletNode"  and weight = 128.01 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
