/**
 * @id prebid/navigator-hardwareconcurrency
 * @name Access to navigator.hardwareConcurrency
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.hardwareConcurrency
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("hardwareConcurrency")
select api, "hardwareConcurrency is an indicator of fingerprinting, weighed 63.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
