// this file is autogenerated, see fingerprintApis.mjs

class GlobalVar extends string {

  float weight; 
  
  GlobalVar() {
      
      ( this = "devicePixelRatio"  and weight = 18.91 )
       or 
      ( this = "screenX"  and weight = 355.18 )
       or 
      ( this = "screenY"  and weight = 309.2 )
       or 
      ( this = "outerWidth"  and weight = 109.86 )
       or 
      ( this = "outerHeight"  and weight = 178.05 )
       or 
      ( this = "screenLeft"  and weight = 374.27 )
       or 
      ( this = "screenTop"  and weight = 373.73 )
       or 
      ( this = "indexedDB"  and weight = 18.81 )
       or 
      ( this = "openDatabase"  and weight = 134.7 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
