/**
 * @id prebid/screen-availleft
 * @name Access to screen.availLeft
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.availLeft
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("availLeft")
select api, "availLeft is an indicator of fingerprinting, weighed 617.51 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
