// this file is autogenerated, see fingerprintApis.mjs

class DOMMethod extends string {

  float weight; 
  string type; 
  
  DOMMethod() {
      
      ( this = "getChannelData"  and weight = 827.19  and type = "AudioBuffer" )
       or 
      ( this = "toDataURL"  and weight = 27.15  and type = "HTMLCanvasElement" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getType() {
    result = type
  }
  
} 
