// this file is autogenerated, see fingerprintApis.mjs

class RenderingContextProperty extends string {

  float weight; 
  string contextType; 
  
  RenderingContextProperty() {
      
      ( this = "getExtension"  and weight = 23.24  and contextType = "webgl" )
       or 
      ( this = "getParameter"  and weight = 27.29  and contextType = "webgl" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 665.75  and contextType = "webgl" )
       or 
      ( this = "getContextAttributes"  and weight = 1417.95  and contextType = "webgl" )
       or 
      ( this = "getSupportedExtensions"  and weight = 1009.79  and contextType = "webgl" )
       or 
      ( this = "getImageData"  and weight = 46.91  and contextType = "2d" )
       or 
      ( this = "getExtension"  and weight = 81.11  and contextType = "webgl2" )
       or 
      ( this = "getParameter"  and weight = 78.86  and contextType = "webgl2" )
       or 
      ( this = "getSupportedExtensions"  and weight = 668.35  and contextType = "webgl2" )
       or 
      ( this = "getContextAttributes"  and weight = 197.1  and contextType = "webgl2" )
       or 
      ( this = "getShaderPrecisionFormat"  and weight = 138.38  and contextType = "webgl2" )
       or 
      ( this = "readPixels"  and weight = 20.79  and contextType = "webgl" )
       or 
      ( this = "isPointInPath"  and weight = 6159.48  and contextType = "2d" )
       or 
      ( this = "measureText"  and weight = 40.71  and contextType = "2d" )
       or 
      ( this = "readPixels"  and weight = 72.72  and contextType = "webgl2" )
  }  

  float getWeight() {
    result = weight
  }
  
  string getContextType() {
    result = contextType
  }
  
} 
