/**
 * @id prebid/intl-datetimeformat-resolvedoptions
 * @name Access to Intl-DateTimeFormat.resolvedOptions
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Intl-DateTimeFormat.resolvedOptions
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode inst, SourceNode api
where
  inst = callTo("Intl", "DateTimeFormat") and
  api = inst.getAPropertyRead("resolvedOptions")
select api, "resolvedOptions is an indicator of fingerprinting, weighed 17.99 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
