/**
 * @id prebid/deviceorientation-alpha
 * @name Access to deviceorientation.alpha
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of alpha on deviceorientation events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("deviceorientation") and
  api = event.getAPropertyRead("alpha")
select api, "alpha is an indicator of fingerprinting, weighed 366.53 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
