// this file is autogenerated, see fingerprintApis.mjs

class GlobalVar extends string {

  float weight; 
  
  GlobalVar() {
      
      ( this = "devicePixelRatio"  and weight = 15.37 )
       or 
      ( this = "screenX"  and weight = 425.14 )
       or 
      ( this = "screenY"  and weight = 399.3 )
       or 
      ( this = "outerWidth"  and weight = 118.62 )
       or 
      ( this = "outerHeight"  and weight = 187.18 )
       or 
      ( this = "screenLeft"  and weight = 345.98 )
       or 
      ( this = "screenTop"  and weight = 344.76 )
       or 
      ( this = "indexedDB"  and weight = 22.13 )
       or 
      ( this = "openDatabase"  and weight = 32.7 )
  }  

  float getWeight() {
    result = weight
  }
  
} 
