/**
 * @id prebid/screen-orientation
 * @name Access to screen.orientation
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.orientation
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("orientation")
select api, "orientation is an indicator of fingerprinting, weighed 44.76 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
