/**
 * @id prebid/navigator-appcodename
 * @name Access to navigator.appCodeName
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.appCodeName
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("appCodeName")
select api, "appCodeName is an indicator of fingerprinting, weighed 143.58 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
