/**
 * @id prebid/navigator-devicememory
 * @name Access to navigator.deviceMemory
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.deviceMemory
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("deviceMemory")
select api, "deviceMemory is an indicator of fingerprinting, weighed 70.5 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
