/**
 * @id prebid/date-gettimezoneoffset
 * @name Access to Date.getTimezoneOffset
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of Date.getTimezoneOffset
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode inst, SourceNode api
where
  inst = instantiationOf("Date") and
  api = inst.getAPropertyRead("getTimezoneOffset")
select api, "getTimezoneOffset is an indicator of fingerprinting, weighed 16.79 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
