/**
 * @id prebid/window-screentop
 * @name Access to window.screenTop
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.screenTop
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("screenTop")
select api, "screenTop is an indicator of fingerprinting, weighed 329.11 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
