/**
 * @id prebid/webgl2-readpixels
 * @name Access to webgl2 rendering context readPixels
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl2 RenderingContext.readPixels
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl2") and
  api = invocation.getAPropertyRead("readPixels")
select api, "readPixels is an indicator of fingerprinting, weighed 68.7 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
