/**
 * @id prebid/screen-pixeldepth
 * @name Access to screen.pixelDepth
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of screen.pixelDepth
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("screen") and
  api = prop.getAPropertyRead("pixelDepth")
select api, "pixelDepth is an indicator of fingerprinting, weighed 37.72 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
