/**
 * @id prebid/window-screeny
 * @name Access to window.screenY
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of window.screenY
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = windowPropertyRead("screenY")
select api, "screenY is an indicator of fingerprinting, weighed 324.59 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
