/**
 * @id prebid/navigator-online
 * @name Access to navigator.onLine
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.onLine
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("onLine")
select api, "onLine is an indicator of fingerprinting, weighed 19.11 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
