/**
 * @id prebid/webgl-getextension
 * @name Access to webgl rendering context getExtension
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of  webgl RenderingContext.getExtension
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from InvokeNode invocation, SourceNode api
where
  invocation.getCalleeName() = "getContext" and
  invocation.getArgument(0).mayHaveStringValue("webgl") and
  api = invocation.getAPropertyRead("getExtension")
select api, "getExtension is an indicator of fingerprinting, weighed 20.11 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
