/**
 * @id prebid/offlineaudiocontext
 * @name Use of OfflineAudioContext
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of OfflineAudioContext
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode api
where
  api = callTo("OfflineAudioContext")
select api, "OfflineAudioContext is an indicator of fingerprinting, weighed 1135.77 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
