/**
 * @id prebid/navigator-requestmediakeysystemaccess
 * @name Access to navigator.requestMediaKeySystemAccess
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of navigator.requestMediaKeySystemAccess
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import prebid
from SourceNode prop, SourceNode api
where
  prop = windowPropertyRead("navigator") and
  api = prop.getAPropertyRead("requestMediaKeySystemAccess")
select api, "requestMediaKeySystemAccess is an indicator of fingerprinting, weighed 17.34 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
