/**
 * @id prebid/devicemotion-accelerationincludinggravity
 * @name Access to devicemotion.accelerationIncludingGravity
 * @kind problem
 * @problem.severity warning
 * @description Finds uses of accelerationIncludingGravity on devicemotion events
 */
 
// this file is autogenerated, see fingerprintApis.mjs

import event
from SourceNode event, SourceNode api
where
  event = domEvent("devicemotion") and
  api = event.getAPropertyRead("accelerationIncludingGravity")
select api, "accelerationIncludingGravity is an indicator of fingerprinting, weighed 149.23 in https://raw.githubusercontent.com/duckduckgo/tracker-radar/refs/heads/main/build-data/generated/api_fingerprint_weights.json"
