name: Wait for browserstack sessions
description: Wait until enough browserstack sessions have become available
inputs:
  sessions:
    description: Number of sessions needed to continue
    default: "6"
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        while            
          status=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" \
            -X GET "https://api-cloud.browserstack.com/automate/plan.json" 2> /dev/null);
          running=$(jq '.parallel_sessions_running' <<< $status)
          max_running=$(jq '.parallel_sessions_max_allowed' <<< $status)
          queued=$(jq '.queued_sessions' <<< $status)
          max_queued=$(jq '.queued_sessions_max_allowed' <<< $status)
          spare=$(( ${max_running} + ${max_queued} - ${running} - ${queued} ))
          required=${{ inputs.sessions }}
          echo "Browserstack status: ${running} sessions running, ${queued} queued, ${spare} free"
          (( ${required} > ${spare} ))
        do
          delay=$(( 60 + $(shuf -i 1-60 -n 1) ))
          echo "Waiting for ${required} sessions to free up, checking again in ${delay}s"
          sleep $delay
        done
