import puppeteer from 'puppeteer'
import process from 'process';

export default async () => {
  const browser = await puppeteer.launch({
    executablePath: process.env.CHROME_BIN ?? '/usr/bin/google-chrome',
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox'
    ]
  })
  const page = await browser.newPage()
  await page.goto('http://localhost:9999/metadata/extractMetadata.html')
  const metadata = await page.evaluate(() => {
    return pbjs._getModuleMetadata()
  })
  await browser.close()
  return {
    NOTICE: "do not edit - this file is automatically generated by `gulp update-metadata`",
    components: metadata
  }
}
