'use strict';

import { registerBidder } from '../src/adapters/bidderFactory.js';
import { BANNER, VIDEO } from '../src/mediaTypes.js';
import { deepAccess, logWarn, deepSetValue } from '../src/utils.js';
import { ortbConverter } from '../libraries/ortbConverter/converter.js';
/** @import { MagicBidParams } from './magicbidBidAdapter.d.ts' */

// ─────────────────────────────────────────────
//  MagicBid Prebid.js Bid Adapter
//  Bidder Code : magicbid
//  Supported   : Banner, Video
// ─────────────────────────────────────────────
//
//  Each publisher receives TWO values from MagicBid:
//    host       → e.g. 'ads-2j0kac.rtb-magicbid.ai'  (unique per publisher,
//                 generated by the Limelight platform when a new publisher
//                 endpoint is created)
//    adUnitId   → e.g. 631967104  (unique per ad placement)
//
//  adUnitType is NOT required — the adapter infers it automatically
//  from the mediaTypes object on the ad unit.
// ─────────────────────────────────────────────

const BIDDER_CODE = 'magicbid';
const DEFAULT_NET_REVENUE = true;
const DEFAULT_TTL = 300;
const MTYPE_MAP = { 1: BANNER, 2: VIDEO };

// ─── ortbConverter ──────────────────────────
// Builds a standard OpenRTB 2.x BidRequest and parses the BidResponse.
// Mirrors the pattern used by the Limelight adapter (which also targets /ortbhb).

const converter = ortbConverter({
  context: {
    netRevenue: DEFAULT_NET_REVENUE,
    ttl: DEFAULT_TTL,
  },

  imp(buildImp, bidRequest, context) {
    const imp = buildImp(bidRequest, context);
    // Embed MagicBid-specific params into imp.ext so the server can route the request.
    deepSetValue(imp, 'ext.magicbid.adUnitId', bidRequest.params.adUnitId);
    deepSetValue(imp, 'ext.magicbid.host', bidRequest.params.host);
    // Optional custom targeting params
    for (let i = 1; i <= 5; i++) {
      const val = bidRequest.params[`custom${i}`];
      if (val !== undefined) deepSetValue(imp, `ext.magicbid.custom${i}`, val);
    }
    return imp;
  },

  bidResponse(buildBidResponse, bid, context) {
    // Determine media type from mtype field (OpenRTB 2.6) or fall back to imp shape.
    let mediaType;
    if (bid.mtype) {
      mediaType = MTYPE_MAP[bid.mtype];
    }
    if (!mediaType && bid.ext?.mediaType) {
      mediaType = bid.ext.mediaType;
    }
    if (!mediaType && context.imp) {
      if (context.imp.banner) mediaType = BANNER;
      else if (context.imp.video) mediaType = VIDEO;
    }
    if (mediaType) context.mediaType = mediaType;
    return buildBidResponse(bid, context);
  },
});

// ─── Helpers ────────────────────────────────

/**
 * Validate that a required string parameter exists and is non-empty.
 */
function validateStringParam(params, paramName) {
  const val = params[paramName];
  if (typeof val !== 'string' || val.trim() === '') {
    logWarn('[MagicBid] Missing or invalid required param: "' + paramName + '"');
    return false;
  }
  return true;
}

/**
 * Validate that a required integer param is a positive integer.
 */
function validateIntParam(params, paramName) {
  const val = params[paramName];
  if (!Number.isInteger(val) || val <= 0) {
    logWarn('[MagicBid] Missing or invalid required param: "' + paramName + '" (must be a positive integer)');
    return false;
  }
  return true;
}

/**
 * Check a bid response object has the minimum fields needed to render.
 */
function isBidResponseValid(bid) {
  if (!bid.requestId || !bid.cpm || !bid.creativeId || !bid.ttl || !bid.currency) {
    return false;
  }
  switch (bid.mediaType) {
    case BANNER:
      return Boolean(bid.width && bid.height && bid.ad);
    case VIDEO:
      return Boolean(bid.vastXml || bid.vastUrl);
  }
  return false;
}

// ─── Adapter Definition ──────────────────────

export const spec = {
  code: BIDDER_CODE,
  supportedMediaTypes: [BANNER, VIDEO],

  // ─── 1. isBidRequestValid ───────────────────
  /**
   * Required params: host, adUnitId
   * adUnitType is optional — inferred from mediaTypes automatically
   */
  isBidRequestValid(bid) {
    const params = bid.params || {};

    if (!validateStringParam(params, 'host')) return false;
    if (!validateIntParam(params, 'adUnitId')) return false;

    // If adUnitType is explicitly provided, validate it
    if (params.adUnitType) {
      const t = params.adUnitType.toLowerCase();
      if (t !== BANNER && t !== VIDEO) {
        logWarn('[MagicBid] adUnitType must be "banner" or "video", got: "' + params.adUnitType + '"');
        return false;
      }
    }

    return true;
  },

  // ─── 2. buildRequests ───────────────────────
  /**
   * Group valid bid requests by host and send one standard OpenRTB request
   * per host to the /ortbhb endpoint.
   */
  buildRequests(validBidRequests, bidderRequest) {
    // Group bids by publisher host (each host = one RTB endpoint)
    const bidsByHost = validBidRequests.reduce((groups, bid) => {
      const host = bid.params.host;
      groups[host] = groups[host] || [];
      groups[host].push(bid);
      return groups;
    }, {});

    const enrichedBidderRequest = {
      ...bidderRequest,
      ortb2: {
        ...bidderRequest.ortb2,
        site: {
          ...bidderRequest.ortb2?.site,
          page: bidderRequest.ortb2?.site?.page || deepAccess(bidderRequest, 'refererInfo.page'),
        },
      },
    };

    return Object.entries(bidsByHost).map(([host, bids]) => ({
      method: 'POST',
      url: 'https://' + host + '/ortbhb',
      data: converter.toORTB({ bidRequests: bids, bidderRequest: enrichedBidderRequest }),
      options: {
        // text/plain avoids a CORS preflight, reducing latency on the hot path.
        contentType: 'text/plain',
        withCredentials: true,
      },
    }));
  },

  // ─── 3. interpretResponse ───────────────────
  interpretResponse(serverResponse, request) {
    if (!serverResponse.body) {
      logWarn('[MagicBid] Empty or missing response body');
      return [];
    }
    return converter
      .fromORTB({ response: serverResponse.body, request: request.data })
      .bids.filter(isBidResponseValid);
  },

  // ─── 4. getUserSyncs ────────────────────────
  getUserSyncs(syncOptions, serverResponses) {
    const syncs = [];
    if (!serverResponses || serverResponses.length === 0) return syncs;

    serverResponses.forEach(function(response) {
      const syncData = deepAccess(response, 'body.ext.userSyncs');
      if (!Array.isArray(syncData)) return;

      syncData.forEach(function(sync) {
        if (sync.type === 'image' && syncOptions.pixelEnabled) {
          syncs.push({ type: 'image', url: sync.url });
        } else if (sync.type === 'iframe' && syncOptions.iframeEnabled) {
          syncs.push({ type: 'iframe', url: sync.url });
        }
      });
    });

    return syncs;
  },

  // ─── 5. onBidWon ────────────────────────────
  onBidWon(bid) {
    if (bid.nurl) {
      fetch(bid.nurl, { method: 'GET', keepalive: true }).catch(function() {});
    }
  },

  // ─── 6. onTimeout ───────────────────────────
  onTimeout(timeoutData) {
    logWarn('[MagicBid] Bid timed out:', timeoutData);
  },
};

registerBidder(spec);
