'use strict';

import { registerBidder } from '../src/adapters/bidderFactory.js';
import { BANNER, VIDEO } from '../src/mediaTypes.js';
import { deepAccess, logWarn } from '../src/utils.js';
/** @import { MagicBidParams } from './magicbidBidAdapter.d.ts' */

// ─────────────────────────────────────────────
//  MagicBid Prebid.js Bid Adapter
//  Bidder Code : magicbid
//  Supported   : Banner, Video
// ─────────────────────────────────────────────
//
//  Each publisher receives TWO values from MagicBid:
//    host       → e.g. 'ads-2j0kac.rtb-magicbid.ai'  (unique per publisher,
//                 generated by the Limelight platform when a new publisher
//                 endpoint is created)
//    adUnitId   → e.g. 631967104  (unique per ad placement)
//
//  adUnitType is NOT required — the adapter infers it automatically
//  from the mediaTypes object on the ad unit.
// ─────────────────────────────────────────────

const BIDDER_CODE = 'magicbid';

// ─── Helpers ────────────────────────────────

/**
 * Determine adUnitType from the bid's mediaTypes object.
 * VIDEO takes priority if both are present.
 * The host is NOT static — it is unique per publisher and is provided
 * by MagicBid during onboarding (generated by the Limelight platform).
 */
function resolveAdUnitType(bid) {
  if (deepAccess(bid, 'mediaTypes.video')) return VIDEO;
  if (deepAccess(bid, 'mediaTypes.banner')) return BANNER;
  // Fall back to explicit param if mediaTypes is not set
  const paramType = (bid.params.adUnitType || '').toLowerCase();
  if (paramType === VIDEO || paramType === BANNER) return paramType;
  return BANNER;
}

/**
 * Build the RTB endpoint URL from the publisher-supplied host.
 * The host is publisher-specific and NOT static — each publisher
 * receives a unique host from MagicBid during onboarding.
 * e.g. host = 'ads-2j0kac.rtb-magicbid.ai'  (unique per publisher)
 *      type  = 'banner'
 *      → 'https://ads-2j0kac.rtb-magicbid.ai/prebid/banner'
 */
function buildEndpointUrl(host, adUnitType) {
  const path = adUnitType === VIDEO ? 'vast' : 'banner';
  return 'https://' + host + '/prebid/' + path;
}

/**
 * Validate that a required string parameter exists and is non-empty.
 */
function validateStringParam(params, paramName) {
  const val = params[paramName];
  if (typeof val !== 'string' || val.trim() === '') {
    logWarn('[MagicBid] Missing or invalid required param: "' + paramName + '"');
    return false;
  }
  return true;
}

/**
 * Validate that a required integer param is a positive integer.
 */
function validateIntParam(params, paramName) {
  const val = params[paramName];
  if (!Number.isInteger(val) || val <= 0) {
    logWarn('[MagicBid] Missing or invalid required param: "' + paramName + '" (must be a positive integer)');
    return false;
  }
  return true;
}

/**
 * Normalize video playerSize — handles both flat [w, h] and
 * nested [[w, h]] forms that publishers may use.
 */
function normalizePlayerSize(playerSize) {
  if (!playerSize) return [];
  // Nested: [[640, 480]] → return as-is
  if (Array.isArray(playerSize[0])) return playerSize;
  // Flat: [640, 480] → wrap in array
  return [playerSize];
}

// ─── Adapter Definition ──────────────────────

export const spec = {
  code: BIDDER_CODE,
  supportedMediaTypes: [BANNER, VIDEO],

  // ─── 1. isBidRequestValid ───────────────────
  /**
   * Required params: host, adUnitId
   * adUnitType is optional — inferred from mediaTypes automatically
   */
  isBidRequestValid(bid) {
    const params = bid.params || {};

    if (!validateStringParam(params, 'host')) return false;
    if (!validateIntParam(params, 'adUnitId')) return false;

    // If adUnitType is explicitly provided, validate it
    if (params.adUnitType) {
      const t = params.adUnitType.toLowerCase();
      if (t !== BANNER && t !== VIDEO) {
        logWarn('[MagicBid] adUnitType must be "banner" or "video", got: "' + params.adUnitType + '"');
        return false;
      }
    }

    return true;
  },

  // ─── 2. buildRequests ───────────────────────
  /**
   * Group valid bid requests by host+adUnitType combination and
   * fire one HTTP request per group.
   */
  buildRequests(validBidRequests, bidderRequest) {
    const groups = {};

    validBidRequests.forEach(function(bid) {
      const params = bid.params;
      const host = params.host;
      const adUnitId = params.adUnitId;

      // Infer adUnitType from mediaTypes — no longer required as a param
      const resolvedType = resolveAdUnitType(bid);

      const key = host + '__' + resolvedType;

      if (!groups[key]) {
        groups[key] = {
          url: buildEndpointUrl(host, resolvedType),
          adUnitType: resolvedType,
          bids: [],
        };
      }

      // Collect ad sizes
      let sizes = [];
      if (resolvedType === BANNER) {
        sizes = deepAccess(bid, 'mediaTypes.banner.sizes') || bid.sizes || [];
      } else if (resolvedType === VIDEO) {
        const playerSize = deepAccess(bid, 'mediaTypes.video.playerSize');
        sizes = normalizePlayerSize(playerSize);
      }

      const bidData = {
        bidId: bid.bidId,
        transactionId: deepAccess(bid, 'ortb2Imp.ext.tid') || bid.transactionId,
        adUnitCode: bid.adUnitCode,
        adUnitId: adUnitId,
        sizes: sizes,
        // Internal reference — stripped before sending to server
        _sourceBid: bid,
      };

      // Optional params
      if (params.publisherId) bidData.publisherId = params.publisherId;
      if (params.custom1) bidData.custom1 = params.custom1;
      if (params.custom2) bidData.custom2 = params.custom2;
      if (params.custom3) bidData.custom3 = params.custom3;
      if (params.custom4) bidData.custom4 = params.custom4;
      if (params.custom5) bidData.custom5 = params.custom5;

      groups[key].bids.push(bidData);
    });

    return Object.values(groups).map(function(group) {
      // Use the first bid from THIS group (not the whole auction)
      // to avoid mixing schain/eids from different publishers
      const representativeBid = group.bids[0]._sourceBid;

      // Read schain from ORTB source path (preferred) or legacy field
      const schain = deepAccess(representativeBid, 'ortb2.source.ext.schain') ||
                     deepAccess(bidderRequest, 'ortb2.source.ext.schain') ||
                     representativeBid.schain || null;

      const eids = representativeBid.userIdAsEids || [];

      return {
        method: 'POST',
        url: group.url,
        data: JSON.stringify({
          id: bidderRequest.auctionId,
          site: {
            page: deepAccess(bidderRequest, 'refererInfo.page') || window.location.href,
            ref: deepAccess(bidderRequest, 'refererInfo.ref') || document.referrer,
          },
          bids: group.bids.map(function(b) {
            const clean = Object.assign({}, b);
            delete clean._sourceBid;
            return clean;
          }),
          gdpr: {
            applies: !!(deepAccess(bidderRequest, 'gdprConsent.gdprApplies')),
            consent: deepAccess(bidderRequest, 'gdprConsent.consentString') || '',
          },
          usp: bidderRequest.uspConsent || '',
          coppa: !!(deepAccess(bidderRequest, 'ortb2.regs.coppa')),
          gpp: deepAccess(bidderRequest, 'gppConsent.gppString') || '',
          gppSid: deepAccess(bidderRequest, 'gppConsent.applicableSections') || [],
          schain: schain,
          eids: eids,
        }),
        options: {
          // Using text/plain to avoid CORS preflight requests which can
          // increase bidder timeouts. The server must accept text/plain.
          contentType: 'text/plain',
          withCredentials: true,
        },
        _adUnitType: group.adUnitType,
      };
    });
  },

  // ─── 3. interpretResponse ───────────────────
  interpretResponse(serverResponse, request) {
    const bids = [];

    if (!serverResponse || !serverResponse.body) {
      logWarn('[MagicBid] Empty or missing response body');
      return bids;
    }

    const adUnitType = request._adUnitType;
    const rawBids = Array.isArray(serverResponse.body)
      ? serverResponse.body
      : [serverResponse.body];

    rawBids.forEach(function(rawBid) {
      if (!rawBid || !rawBid.cpm || rawBid.cpm <= 0) return;

      const bid = {
        requestId: rawBid.bidId,
        cpm: rawBid.cpm,
        currency: rawBid.currency || 'USD',
        width: rawBid.width || 0,
        height: rawBid.height || 0,
        creativeId: rawBid.creativeId || rawBid.bidId,
        dealId: rawBid.dealId || null,
        netRevenue: true,
        ttl: rawBid.ttl || 300,
        // Preserve nurl for win notification in onBidWon
        nurl: rawBid.nurl || null,
        meta: {
          advertiserDomains: rawBid.adomain || [],
        },
      };

      if (adUnitType === VIDEO) {
        bid.mediaType = VIDEO;
        bid.vastUrl = rawBid.vastUrl || rawBid.ad;
        bid.vastXml = rawBid.vastXml || null;
      } else {
        bid.mediaType = BANNER;
        bid.ad = rawBid.ad;
      }

      bids.push(bid);
    });

    return bids;
  },

  // ─── 4. getUserSyncs ────────────────────────
  getUserSyncs(syncOptions, serverResponses) {
    const syncs = [];
    if (!serverResponses || serverResponses.length === 0) return syncs;

    serverResponses.forEach(function(response) {
      const syncData = deepAccess(response, 'body.userSyncs');
      if (!Array.isArray(syncData)) return;

      syncData.forEach(function(sync) {
        if (sync.type === 'image' && syncOptions.pixelEnabled) {
          syncs.push({ type: 'image', url: sync.url });
        } else if (sync.type === 'iframe' && syncOptions.iframeEnabled) {
          syncs.push({ type: 'iframe', url: sync.url });
        }
      });
    });

    return syncs;
  },

  // ─── 5. onBidWon ────────────────────────────
  onBidWon(bid) {
    if (bid.nurl) {
      fetch(bid.nurl, { method: 'GET', keepalive: true }).catch(function() {});
    }
  },

  // ─── 6. onTimeout ───────────────────────────
  onTimeout(timeoutData) {
    logWarn('[MagicBid] Bid timed out:', timeoutData);
  },
};

registerBidder(spec);
