'use strict';

import { registerBidder } from '../src/adapters/bidderFactory.js';
import { BANNER, VIDEO } from '../src/mediaTypes.js';
import { deepAccess, logWarn } from '../src/utils.js';

// ─────────────────────────────────────────────
//  MagicBid Prebid.js Bid Adapter
//  Bidder Code : magicbid
//  Supported   : Banner, Video
// ─────────────────────────────────────────────
//
//  Each publisher receives THREE values from MagicBid:
//    host       → e.g. 'ads-2j0kac.rtb-magicbid.ai'  (unique per publisher)
//    adUnitId   → e.g. 631967104                       (unique per ad placement)
//    adUnitType → 'banner' or 'video'
//
//  The host is publisher-specific and is generated by the Limelight
//  platform when a new publisher endpoint is created. MagicBid passes
//  this value to the publisher during onboarding.
// ─────────────────────────────────────────────

const BIDDER_CODE = 'magicbid';
const GVLID = undefined; // Add your IAB GVL ID here once registered

// ─── Helpers ────────────────────────────────

/**
 * Build the RTB endpoint URL from the publisher-supplied host.
 * Each publisher has a unique host assigned by MagicBid (via Limelight).
 * e.g. host = 'ads-2j0kac.rtb-magicbid.ai'
 *      type  = 'banner'
 *      → 'https://ads-2j0kac.rtb-magicbid.ai/prebid/banner'
 */
function buildEndpointUrl(host, adUnitType) {
  const path = adUnitType === VIDEO ? 'vast' : 'banner';
  return `https://${host}/prebid/${path}`;
}

/**
 * Validate that a required string parameter exists and is non-empty.
 */
function validateStringParam(params, paramName) {
  const val = params[paramName];
  if (typeof val !== 'string' || val.trim() === '') {
    logWarn(`[MagicBid] Missing or invalid required param: "${paramName}"`);
    return false;
  }
  return true;
}

/**
 * Validate that a required integer param is a positive integer.
 */
function validateIntParam(params, paramName) {
  const val = params[paramName];
  if (!Number.isInteger(val) || val <= 0) {
    logWarn(`[MagicBid] Missing or invalid required param: "${paramName}" (must be a positive integer)`);
    return false;
  }
  return true;
}

// ─── Adapter Definition ──────────────────────

export const spec = {
  code: BIDDER_CODE,
  gvlid: GVLID,
  supportedMediaTypes: [BANNER, VIDEO],

  // ─── 1. isBidRequestValid ───────────────────
  /**
   * All three params are required for every bid request.
   *   host       : publisher-specific RTB endpoint host (given by MagicBid)
   *   adUnitId   : placement ID (given by MagicBid)
   *   adUnitType : 'banner' or 'video'
   */
  isBidRequestValid(bid) {
    const params = bid.params || {};

    if (!validateStringParam(params, 'host')) return false;
    if (!validateIntParam(params, 'adUnitId')) return false;
    if (!validateStringParam(params, 'adUnitType')) return false;

    const adUnitType = params.adUnitType.toLowerCase();
    if (adUnitType !== BANNER && adUnitType !== VIDEO) {
      logWarn(`[MagicBid] adUnitType must be "banner" or "video", got: "${params.adUnitType}"`);
      return false;
    }

    return true;
  },

  // ─── 2. buildRequests ───────────────────────
  /**
   * Group bids by host+adUnitType so that all placements sharing the
   * same endpoint are sent in one HTTP request.
   */
  buildRequests(validBidRequests, bidderRequest) {
    const groups = {};

    validBidRequests.forEach(bid => {
      const {
        host, adUnitType, adUnitId, publisherId,
        custom1, custom2, custom3, custom4, custom5,
      } = bid.params;

      const resolvedType = adUnitType.toLowerCase();

      // Group key: one request per unique host+adUnitType pair
      const key = `${host}__${resolvedType}`;

      if (!groups[key]) {
        groups[key] = {
          url: buildEndpointUrl(host, resolvedType),
          adUnitType: resolvedType,
          bids: [],
        };
      }

      // Collect ad sizes
      let sizes = [];
      if (resolvedType === BANNER) {
        sizes = deepAccess(bid, 'mediaTypes.banner.sizes') || bid.sizes || [];
      } else if (resolvedType === VIDEO) {
        const playerSize = deepAccess(bid, 'mediaTypes.video.playerSize');
        sizes = playerSize ? [playerSize[0]] : bid.sizes || [];
      }

      const bidData = {
        bidId: bid.bidId,
        transactionId: bid.ortb2Imp?.ext?.tid || bid.transactionId,
        adUnitCode: bid.adUnitCode,
        adUnitId,
        sizes,
      };

      // publisherId is optional on client-side
      if (publisherId) bidData.publisherId = publisherId;

      // Optional custom targeting params
      if (custom1) bidData.custom1 = custom1;
      if (custom2) bidData.custom2 = custom2;
      if (custom3) bidData.custom3 = custom3;
      if (custom4) bidData.custom4 = custom4;
      if (custom5) bidData.custom5 = custom5;

      groups[key].bids.push(bidData);
    });

    return Object.values(groups).map(group => ({
      method: 'POST',
      url: group.url,
      data: JSON.stringify({
        id: bidderRequest.auctionId,
        site: {
          page: bidderRequest.refererInfo?.page || window.location.href,
          ref: bidderRequest.refererInfo?.ref || document.referrer,
        },
        bids: group.bids,
        gdpr: {
          applies: !!(bidderRequest.gdprConsent?.gdprApplies),
          consent: bidderRequest.gdprConsent?.consentString || '',
        },
        usp: bidderRequest.uspConsent || '',
        coppa: !!(deepAccess(bidderRequest, 'ortb2.regs.coppa')),
        gpp: bidderRequest.gppConsent?.gppString || '',
        gppSid: bidderRequest.gppConsent?.applicableSections || [],
        schain: validBidRequests[0]?.schain || null,
        eids: validBidRequests[0]?.userIdAsEids || [],
      }),
      options: {
        contentType: 'application/json',
        withCredentials: true,
      },
      _adUnitType: group.adUnitType,
    }));
  },

  // ─── 3. interpretResponse ───────────────────
  /**
   * Parse the RTB response from the MagicBid endpoint and return
   * an array of valid Prebid bid objects.
   */
  interpretResponse(serverResponse, request) {
    const bids = [];

    if (!serverResponse?.body) {
      logWarn('[MagicBid] Empty or missing response body');
      return bids;
    }

    const adUnitType = request._adUnitType;
    const rawBids = Array.isArray(serverResponse.body)
      ? serverResponse.body
      : [serverResponse.body];

    rawBids.forEach(rawBid => {
      if (!rawBid || !rawBid.cpm || rawBid.cpm <= 0) return;

      const bid = {
        requestId: rawBid.bidId,
        cpm: rawBid.cpm,
        currency: rawBid.currency || 'USD',
        width: rawBid.width || 0,
        height: rawBid.height || 0,
        creativeId: rawBid.creativeId || rawBid.bidId,
        dealId: rawBid.dealId || null,
        netRevenue: true,
        ttl: rawBid.ttl || 300,
        meta: {
          advertiserDomains: rawBid.adomain || [],
        },
      };

      if (adUnitType === VIDEO) {
        bid.mediaType = VIDEO;
        bid.vastUrl = rawBid.vastUrl || rawBid.ad;
        bid.vastXml = rawBid.vastXml || null;
      } else {
        bid.mediaType = BANNER;
        bid.ad = rawBid.ad;
      }

      bids.push(bid);
    });

    return bids;
  },

  // ─── 4. getUserSyncs ────────────────────────
  getUserSyncs(syncOptions, serverResponses) {
    const syncs = [];
    if (!serverResponses || serverResponses.length === 0) return syncs;

    serverResponses.forEach(response => {
      const syncData = response?.body?.userSyncs;
      if (!Array.isArray(syncData)) return;

      syncData.forEach(sync => {
        if (sync.type === 'image' && syncOptions.pixelEnabled) {
          syncs.push({ type: 'image', url: sync.url });
        } else if (sync.type === 'iframe' && syncOptions.iframeEnabled) {
          syncs.push({ type: 'iframe', url: sync.url });
        }
      });
    });

    return syncs;
  },

  // ─── 5. onBidWon ────────────────────────────
  onBidWon(bid) {
    if (bid.nurl) {
      fetch(bid.nurl, { method: 'GET', keepalive: true }).catch(() => {});
    }
  },

  // ─── 6. onTimeout ───────────────────────────
  onTimeout(timeoutData) {
    logWarn('[MagicBid] Bid timed out:', timeoutData);
  },
};

registerBidder(spec);
