name: Clear browserstack sessions
description: Close pending browserstack sessions

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        for id in $(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" -X GET "https://api-cloud.browserstack.com/automate/builds.json?status=running" 2> /dev/null | jq '.[].automation_build | select(.name == '"$BROWSERSTACK_BUILD_NAME"') | .hashed_id'); 
        do
          echo "Deleting session: ${id}"
          curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" -X DELETE "https://api.browserstack.com/automate/sessions/${id}.json"  
        done
        
