name: Clear browserstack sessions
description: Close pending browserstack sessions

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [ -n "$BROWSERSTACK_USERNAME" ]; then 
          for build_id in $(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" -X GET "https://api-cloud.browserstack.com/automate/builds.json?status=running" 2> /dev/null | jq -r '.[].automation_build | select(.name == "'"$BROWSERSTACK_BUILD_NAME"'") | .hashed_id'); 
          do
            sessions=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" -X GET "https://api-cloud.browserstack.com/automate/builds/${build_id}/sessions.json?status=running" 2> /dev/null)
            for session_id in $(jq -r '.[].automation_session.hashed_id' <<< $sessions);
            do
              echo "Deleting session: ${session_id}"
              curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" -X DELETE "https://api.browserstack.com/automate/sessions/${session_id}.json" 2> /dev/null  
            done
          done        
        fi
        true
