import {PbPromise} from './utils/promise.js';
import {createInvisibleIframe} from './utils.js';
// eslint-disable-next-line prebid/validate-imports
import {RENDERER} from '../creative-renderers/display.js'; // autogenerated during precompilation
import {hook} from './hook.js';

// the minimum rendererVersion that will be used by PUC
export const PUC_MIN_VERSION = 3;

export const getCreativeRendererSource = hook('sync', function (bidResponse) {
  return RENDERER;
})

export const getCreativeRenderer = (function() {
  const renderers = {};
  return function (bidResponse) {
    const src = getCreativeRendererSource(bidResponse);
    if (!renderers.hasOwnProperty(src)) {
      renderers[src] = new PbPromise((resolve) => {
        const iframe = createInvisibleIframe()
        iframe.srcdoc = `
            <script>${src}</script>
            <script>
              window.parent.postMessage(
                  { type: 'RENDERER_READY_${bidResponse.adId}' },
                  '*'
            );</script>`;
        const listenerForRendererReady = (event) => {
          if (event.source !== iframe.contentWindow) return;
          if (event.data?.type === `RENDERER_READY_${bidResponse.adId}`) {
            window.removeEventListener('message', listenerForRendererReady);
            resolve(iframe.contentWindow.render);
          }
        }
        window.addEventListener('message', listenerForRendererReady);
        document.body.appendChild(iframe);
      })
    }
    return renderers[src];
  }
})();
