name: Code coverage report
on:
  workflow_run:
    workflows:
      - Run tests
    types:
      - completed
permissions:
  actions: read

jobs:
  barecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: master
      - name: Fetch base branch coverage
        uses: ./.github/actions/unzip-artifact
        with:
          name: "base-coverage.info"
      - name: Fetch PR coverage
        uses: ./.github/actions/unzip-artifact
        with:
          name: "coverage.info"
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "${{ runner.temp }}/artifacts/coverage.info"
          base-lcov-file: "${{ runner.temp }}/artifacts/base-coverage.info"
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
