name: Notify Code Path Changes

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - '**'

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NOTIFICATION_EMAIL: 'prebid-notifications@prebid.org'
  NOTIFICATION_PASSWORD: ${{ secrets.NOTIFICATION_PASSWORD }}

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install nodemailer@8.0.5

      - name: Run Notification Script
        run: |
          node .github/workflows/scripts/send-notification-on-change.js
