name: Post a comment
on:
  workflow_run:
    workflows:
      - Check for Duplicated Code
      - Check for linter warnings / exceptions
      - Check adapter naming conventions
      - Build metadata
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: master
      - name: Retrieve comment data
        id: get-comment
        uses: ./.github/actions/unzip-artifact
        with:
          name: comment

      - name: 'Comment on PR'
        if: ${{ steps.get-comment.outputs.exists == 'true' }}
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const temp = '${{ runner.temp }}/artifacts';
            let {issue_number, body} = JSON.parse(fs.readFileSync(path.join(temp, 'comment.json')));
            const whoami = 'github-actions[bot]';
            const tag = `<!-- Workflow: "${{ github.event.workflow_run.name }}" -->`;
            body = body + '\n' + tag;
            
            const request = (args) => Object.assign({owner: context.repo.owner, repo: context.repo.repo}, args);
            
            const previousComment = (await github.rest.issues.listComments(request({issue_number})))
              .data
              .find(comment => comment.user.login === whoami && comment.body.includes(tag));
            
            if (previousComment == null ) {
               await github.rest.issues.createComment(request({issue_number, body}));
            } else if (previousComment.body !== body) {
               await github.rest.issues.updateComment(request({comment_id: previousComment.id, body}));              
            }
