import CONSTANTS from '../src/constants.json';
export const MESSAGES = CONSTANTS.MESSAGES;
export const AD_RENDER_SUCCEEDED = CONSTANTS.EVENTS.AD_RENDER_SUCCEEDED;
export const AD_RENDER_FAILED = CONSTANTS.EVENTS.AD_RENDER_FAILED;
export const EXCEPTION = CONSTANTS.AD_RENDER_FAILED_REASON.EXCEPTION;
